
import './globals.css'


export const metadata = {
  manifest:'/manifest.webmanifest',
  title: 'Create Next App',
  description: 'Generated by create next app',
  charset: 'UTF-8',
  icons: {
    apple: '/icon.png',
    other: {
      rel: 'apple-touch-icon',
      url: '/icon.png',
    }
  }
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className='overflow-hidden md:overflow-auto'>{children}</body>
    </html>
  )
}
